# 5.1.2 Numpy Array

<a href='https://docs.scipy.org/doc/numpy/user/quickstart.html'>Dokumentasjon<a/>

### Hente numpy-biblioteket

In [1]:
import numpy as np

### Lage Array med Numpy

#### Manuelt
---

In [2]:
a = np.array([2,7,3])
a

array([2, 7, 3])

In [3]:
a.dtype

dtype('int64')

In [17]:
b = np.sqrt(a)
b

array([1.41421356, 2.64575131, 1.73205081])

In [19]:
b.dtype

dtype('float64')

In [20]:
c = np.array([1, 5, 3+3.j], dtype=complex)
c

array([1.+0.j, 5.+0.j, 3.+3.j])

#### np.zeros
---
Fyller arrayen (matrise i boken) (vector på uio) med 0-ere


In [27]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### np.ones
---
Fyller arrayen (matrise i boken) (vector på uio) med 1-ere

In [28]:
o = np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
a

array([2, 7, 3])

In [30]:
b

array([1.41421356, 2.64575131, 1.73205081])

In [31]:
a*b

array([ 2.82842712, 18.52025918,  5.19615242])

In [32]:
a.dot(b)

26.54483872490496

In [33]:
a@b

26.54483872490496

In [34]:
a+b

array([3.41421356, 9.64575131, 4.73205081])

In [35]:
def f(x):
    return x**2

In [36]:
f(a)

array([ 4, 49,  9])

In [37]:
f(b)

array([2., 7., 3.])

In [39]:
for x in a.flat:
    print(a)

[2 7 3]
[2 7 3]
[2 7 3]


In [40]:
a

array([2, 7, 3])

In [51]:
np.floor(3*np.random.random((10))+1)

array([3., 1., 3., 2., 2., 3., 3., 3., 3., 1.])

In [52]:
len(a)

3