# Numpy Array
<a href='https://docs.scipy.org/doc/numpy/user/quickstart.html'>Dokumentasjon</a>

Et endimensjonal Numpay-Array har mange av de samme egenskapene som en vektor.  

### Importere biblioteket
----

Det finnes mange måter å importere bibliotek på i Python, men detter den den mest ryddige.

Vi har her satt np som alias til numpy

In [4]:
import numpy as np

### Opprette Array
----

#### - Manuelt
---

In [5]:
a = np.array([1,2,6,9,29])
print(a)

[ 1  2  6  9 29]


In [6]:
a.dtype

dtype('int64')

#### - np.zeros
___
fyller en array med 0-ere

In [7]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### - np.ones
___

fyller en array med 1-ere

In [8]:
o = np.ones(10)
print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
print(np.ones(10)*np.pi)

[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
 3.14159265 3.14159265 3.14159265 3.14159265]


#### - np.arange
___

np.arange(fra, til, intervall)

In [10]:
x1 = np.arange(0,10,2)
print(x1)

[0 2 4 6 8]


**Slik gjorde vi det med lister**

In [11]:
[x for x in range(0,10,2)]

[0, 2, 4, 6, 8]

#### - np.linspace
___
np.arange(fra, til og med, antall elementer)

In [12]:
x2 = np.linspace(0,8,5)
print(x2)

[0. 2. 4. 6. 8.]


#### Operasjoner
---

In [13]:
a

array([ 1,  2,  6,  9, 29])

In [14]:
b = np.sqrt(a)
b

array([1.        , 1.41421356, 2.44948974, 3.        , 5.38516481])

**$+$ $-$ $\cdot$ $/$**

In [15]:
print(a + b)

[ 2.          3.41421356  8.44948974 12.         34.38516481]


In [16]:
print(a - b)

[ 0.          0.58578644  3.55051026  6.         23.61483519]


In [17]:
print(a * b)

[  1.           2.82842712  14.69693846  27.         156.16977941]


In [18]:
print(a/b)

[1.         1.41421356 2.44948974 3.         5.38516481]


**Prikkprodukt**

In [20]:
a.dot(b)

201.69514498834585

In [21]:
a@b

201.69514498834585

### Skrive ut
___

In [22]:
print(a)

[ 1  2  6  9 29]


In [26]:
print(b)

[1.         1.41421356 2.44948974 3.         5.38516481]


In [24]:
for e in b:
    print(f'{e:.2f}')

1.00
1.41
2.45
3.00
5.39


### Funksjoner
___

In [75]:
def f(x):
    return x**2

In [76]:
x = np.array([1,2,6,9,29])
y = f(x)

In [77]:
print(y)

[  1   4  36  81 841]
