# Numpy Array
<a href='https://docs.scipy.org/doc/numpy/user/quickstart.html'>Dokumentasjon</a>

### Hente biblioteket
----

In [1]:
import numpy as np

### Opprette Array
----

#### - Manuelt
---

In [69]:
a = np.array([1,2,6,9,29])
print(a)

[ 1  2  6  9 29]


In [68]:
b = np.sqrt(a)
print(b)

[1.         1.41421356 2.44948974 3.         5.38516481]


In [11]:
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('float64')

#### - np.zeros
___
fyller en array med 0-ere

In [78]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### - np.ones
___

fyller en array med 1-ere

In [71]:
o = np.ones(10)
print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [72]:
print(np.ones(10)*np.pi)

[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
 3.14159265 3.14159265 3.14159265 3.14159265]


#### - np.arange
___

np.arange(fra, til, intervall)

In [73]:
x1 = np.arange(0,10,2)
print(x1)

[0 2 4 6 8]


**Slik gjorde vi det med lister**

In [30]:
[x for x in range(0,10,2)]

[0, 2, 4, 6, 8]

#### - np.linspace
___
np.arange(fra, til og med, antall elementer)

In [74]:
x2 = np.linspace(0,8,5)
print(x2)

[0. 2. 4. 6. 8.]


### Printe
___

In [47]:
print(a)

[ 1  2  6  9 29]


In [48]:
print(b)

[1.         1.41421356 2.44948974 3.         5.38516481]


In [55]:
for e in b:
    print(f'{e:.2f}')

1.00
1.41
2.45
3.00
5.39


### Funksjoner
___

In [75]:
def f(x):
    return x**2

In [76]:
x = np.array([1,2,6,9,29])
y = f(x)

In [77]:
print(y)

[  1   4  36  81 841]
