# 6. Tilfeldige tall og spill - Løsningsforslag

#### Importerer de nødvendige bibliotekene

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import random as rd

## 6.1.1 Lister
### Oppgave 5.1
Lag et program som lager:
1. Tilfeldige heltall fra og med −5 til og med 5.
2. Tilfeldige flyttall fra og med 0 til 10.
3. Ei liste med fem tilfeldige tall mellom 100 og 200.
4. Ei liste med fem tilfeldige partall mellom 100 og 200.

#### Løsning:

In [51]:
#1
print(f'(1)  {rd.randrange(-5, 6, 1)}') #(fra, til -1, steg)

#2
print(f'(2)  {rd.uniform(0, 10.0):f}')

#3
femTall = '(3) '
for x in range(5):
    femTall += f'{rd.randrange(100, 201, 1):^5}'
print(femTall)

#4
femPartall = '(4) '
for x in range(5):
    femPartall += f'{rd.randrange(100, 201, 2):^5}'
print(femPartall)

(1)  0
(2)  2.984175
(3)  158  169  194  134  175 
(4)  110  178  130  168  146 


### Oppgave 5.2

In [62]:
rd.randint(0,10)

2

#### Løsning:

In [64]:
from pylab import *
liste1 = uniform(1,100,5)
liste2 = randint(1,100,5)
print(liste1)
print(liste2)

[20.22691694 24.18758018 23.42111074 39.13369398 79.58108497]
[53 30 63 16 69]


In [71]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])